return {
  bash = require('opencode.ui.formatter.tools.bash'),
  read = require('opencode.ui.formatter.tools.file'),
  edit = require('opencode.ui.formatter.tools.file'),
  write = require('opencode.ui.formatter.tools.file'),
  apply_patch = require('opencode.ui.formatter.tools.apply_patch'),
  todowrite = require('opencode.ui.formatter.tools.todowrite'),
  glob = require('opencode.ui.formatter.tools.glob'),
  grep = require('opencode.ui.formatter.tools.grep'),
  webfetch = require('opencode.ui.formatter.tools.webfetch'),
  list = require('opencode.ui.formatter.tools.list'),
  question = require('opencode.ui.formatter.tools.question'),
  task = require('opencode.ui.formatter.tools.task'),
  tool = require('opencode.ui.formatter.tools.tool'),
}
