return {
  bash = require('opencode.ui.formatter.tools.bash'),
  shell = require('opencode.ui.formatter.tools.bash'),
  read = require('opencode.ui.formatter.tools.file'),
  edit = require('opencode.ui.formatter.tools.file'),
  write = require('opencode.ui.formatter.tools.file'),
  apply_patch = require('opencode.ui.formatter.tools.apply_patch'),
  patch = require('opencode.ui.formatter.tools.patch'),
  todowrite = require('opencode.ui.formatter.tools.todowrite'),
  glob = require('opencode.ui.formatter.tools.glob'),
  grep = require('opencode.ui.formatter.tools.grep'),
  webfetch = require('opencode.ui.formatter.tools.webfetch'),
  websearch = require('opencode.ui.formatter.tools.websearch'),
  execute = require('opencode.ui.formatter.tools.execute'),
  list = require('opencode.ui.formatter.tools.list'),
  question = require('opencode.ui.formatter.tools.question'),
  skill = require('opencode.ui.formatter.tools.skill'),
  task = require('opencode.ui.formatter.tools.task'),
  mcp = require('opencode.ui.formatter.tools.mcp'),
  tool = require('opencode.ui.formatter.tools.tool'),
}
